version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one
    platform: linux
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4317:4317"
      - "16686:16686"
      - "13133:13133"
      - "6831:6831/udp"